info:
  application:
    name: USER-SERVICE
    description: User Service
    author:
      name: Ashish Singh
      bio: Geek

server:
  port: 9002

spring:
  application:
    name: USER-SERVICE
  config:
    import: "optional:configserver:"

management:
  endpoints:
    web:
      exposure:
        include: env, health, metrics, beans, info, *
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
    beans:
      enabled: true
  info:
    git:
      mode: full

